default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cook_book_development

test:
  <<: *default
  database: cook_book_test

production:
  <<: *default
  database: cookbook_dj5m
  username: cookbook_dj5m_user
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
